name: Build Application

on:
  push:
    branches-ignore:
      - 'renovate/**'
    paths-ignore:
      - '**.md'
      - '**/LICENSE'
      - 'flake.lock'
      - 'packages/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.markdownlint**'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**/LICENSE'
      - 'flake.lock'
      - 'packages/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.markdownlint**'
  workflow_dispatch:

jobs:

  build_debug:
    name: Build Debug
    uses: ./.github/workflows/build.yml
    with:
      build_type: Debug
      is_qt_cached: true
    secrets:
      SPARKLE_ED25519_KEY: ${{ secrets.SPARKLE_ED25519_KEY }}
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
